### ISSUE TITLE
Web Player Level 3 move error

### ISSUE THREAD

**Issue by Dersinex** [Tactibru/Game#113]
Units can be me moved during the opposite player's turn. I.e. the player can select one of the player units during the player's turn, switch to the enemy's turn and move their select unit and vice versa.

![image](https://f.cloud.github.com/assets/5694936/1387672/7a0adb3c-3ba2-11e3-9ee8-2f380370254f.png)

**Comment by Minalien** [comment]
The way turns end and move on at the moment is for debugging purposes only - in the future, this will not be able to happen.
