### ISSUE TITLE
Web Player Level 3 movement block error

### ISSUE THREAD

**Issue by Dersinex** [Tactibru/Game#114]
What I assume is an invisible fence that's bottom collision starts at 6 blocks up and 9 blocks to the right --from the bottom left corner of the map can be traveled into if the player moves their unit to the block directly underneath the invisible fence.

![image](https://f.cloud.github.com/assets/5694936/1387702/da5a9d0a-3ba3-11e3-9dde-4bcf01953b79.png)

![image](https://f.cloud.github.com/assets/5694936/1387718/735b29b6-3ba4-11e3-825b-9edd4eacd5b2.png)

![image](https://f.cloud.github.com/assets/5694936/1387725/9dc61ad0-3ba4-11e3-8e3b-e34041d6fd21.png)

**Comment by Minalien** [comment]
Fences don't take an entire row or column of movement points, they simply separate two valid movement points from direct connection to each other. The newest build will have grayboxing (or proper fence meshes) in place to display where the fences are.
