### ISSUE TITLE
Web Player Level 3 attack glitch

### ISSUE THREAD

**Issue by Dersinex** [Tactibru/Game#115]
If the player switches unit control fast enough, they can attack units that are still moving to a location. As long as an opposing unit is still within the movement radius of the newly select unit they can attack the moving unit from a distance.

![image](https://f.cloud.github.com/assets/5694936/1387774/b0794ed4-3ba6-11e3-8c02-d5cc82460c59.png)

![image](https://f.cloud.github.com/assets/5694936/1387772/a26ed4a8-3ba6-11e3-8c32-81d34364d075.png)

![image](https://f.cloud.github.com/assets/5694936/1387767/754b68a6-3ba6-11e3-9fc4-789d3ffd9b61.png)

**Comment by Minalien** [comment]
Will fix this by adjusting when players can and cannot move a unit.

**Comment by Minalien** [comment]
Issue is not constrained to a single level.
