### ISSUE TITLE
Crashing issues

### ISSUE THREAD

**Issue by SanTaino** [Tactibru/Game#56]
Level 5: when opening this level, it seems to crash Unity once you move two or in some case one unit.

**Comment by SanTaino** [comment]
FYI the crash happens when the game is fullscreen, not when you window it.

**Comment by DanielRiccardi** [comment]
![image](https://f.cloud.github.com/assets/5694901/1355904/86a07506-376e-11e3-84e8-02150f77d86f.png)
![image](https://f.cloud.github.com/assets/5694901/1355910/a08f75d4-376e-11e3-91a8-78763dc4b18d.png)

Playing level 3
unit selected in the first image was able to move into combat with selected unit outside of its established movement range, was able to move after moving all of my own pieces for the players turn. Selected enemy unit 1st and was able to select player unit and enemy unit managed to move as far as needed to initiate combat.

**Comment by DanielRiccardi** [comment]
![tactibru_1](https://f.cloud.github.com/assets/5694901/1356069/1a93534e-3771-11e3-8488-c2ed2148d08b.jpg)
