### ISSUE TITLE
Units able to be selected while moving

### ISSUE THREAD

**Issue by Hystoriwr** [Tactibru/Game#61]
Units can be selected (clicked) while moving, and if this is done, more movement tiles will appear along the unit's path. These 'extra' tiles can be clicked to move the unit to places it normally couldn't.
![image](https://f.cloud.github.com/assets/5694934/1355931/f0a20dde-376e-11e3-8842-c796920ce778.png)

**Comment by Minalien** [comment]
Fixed.
