### ISSUE TITLE
Units can be selected to move into the same space- Causes crashing

### ISSUE THREAD

**Issue by Hystoriwr** [Tactibru/Game#63]
After a unit is selected to move to a certain tile, if another unit is selected and ordered to the same tile while the first unit is still moving, the game will crash.
![image](https://f.cloud.github.com/assets/5694934/1355982/c25e8500-376f-11e3-95ce-a59f69cb3ee6.png)

**Comment by Minalien** [comment]
Can no longer happen due to when tiles are placed on the ignore list.
