### ISSUE TITLE
Moving two units at the same time

### ISSUE THREAD

**Issue by csg608893** [Tactibru/Game#69]
It is possible for the player to select one unit for movement and then select another unit for movement while the previous unit is still moving.
Level: 3
Version: Windows
![tactibru issue 5](https://f.cloud.github.com/assets/5694889/1356098/98afe706-3771-11e3-8120-4423f38bb3e7.png)

**Comment by Minalien** [comment]
Units cannot interfere with each other when moving anymore, marking this as wontfix.
